version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:30"
      timezone: "Europe/Berlin"
    # Only dependencies maintained by the Vike team
    allow:
      - dependency-name: "@batijs/*"
      - dependency-name: "@brillout/*"
      - dependency-name: "@photonjs/*"
      - dependency-name: "@universal-middleware/*"
      - dependency-name: "react-streaming"
      - dependency-name: "telefunc"
      - dependency-name: "vike-*"
      - dependency-name: "vite-plugin-vercel"
