version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dependencies-we-control:
        patterns:
          - "@brillout/*"
          - "@photonjs/*"
          - "@universal-middleware/*"
          - "telefunc"
          - "vike-*"
          - "vite-plugin-vercel"
