blank_issues_enabled: false
contact_links:
  - name: "ğŸ™ Help & Questions"
    url: https://github.com/vikejs/vike/discussions/new?category=help-questions
    about: "GitHub Discussions: get official help and answers from maintainers."
  - name: "ğŸ—¨ï¸ Other"
    url: https://github.com/vikejs/vike/discussions/new?category=other
    about: "GitHub Discussions: Ideas, complaints, ..."
  - name: "ğŸ’¬ Chit-chat"
    url: https://discord.com/invite/hfHhnJyVg8
    about: "Discord: casual conversation with the community about Vike and broader Software Engineering topics."
