blank_issues_enabled: false
contact_links:
  - name: "ğŸ™ Help & Questions (GitHub Discussions)"
    url: https://github.com/vikejs/vike/discussions/new?category=help-questions
    about: Get official help and answers from maintainers.
  - name: "ğŸ—¨ï¸ Other (GitHub Discussions)"
    url: https://github.com/vikejs/vike/discussions/new?category=other
    about: Ideas, complaints, show-and-tell, ...
  - name: "ğŸ’¬ Chit-chat (Discord)"
    url: https://discord.com/invite/hfHhnJyVg8
    about: Casual conversation with the community about Vike and broader Software Engineering topics.
