blank_issues_enabled: false
contact_links:
  - name: "ğŸ™ Help & Questions"
    url: https://github.com/vikejs/vike/discussions/new?category=help-questions
    about: [GitHub Discussions] Get official help and answers from maintainers.
  - name: "ğŸ—¨ï¸ Other"
    url: https://github.com/vikejs/vike/discussions/new?category=other
    about: [GitHub Discussions] Ideas, complaints, show-and-tell, ...
  - name: "ğŸ’¬ Chit-chat (Discord)"
    url: https://discord.com/invite/hfHhnJyVg8
    about: [Discord] Casual conversation with the community about Vike and broader Software Engineering topics.
