blank_issues_enabled: false
contact_links:
  - name: "ğŸ™ Help"
    url: https://github.com/brillout/vite-plugin-sssr/discussions
    about: Get help.
  - name: "ğŸ’¬ Discussions"
    url: https://discord.com/invite/dSDMGGJZQy
    about: Discussions about vite-plugin-ssr and broader topics.
