blank_issues_enabled: false
contact_links:
  - name: "ğŸ™ Help & Questions"
    url: https://github.com/brillout/vike/discussions
    about: Get help and ask questions.
  - name: "ğŸ’¬ Chit-chat"
    url: https://discord.com/invite/hfHhnJyVg8
    about: Casual conversations about vike and broader topics.
