blank_issues_enabled: false
contact_links:
  - name: "ğŸ’¬ Discord Chat"
    url: https://discord.com/invite/dSDMGGJZQy
    about: Discussions about vite-plugin-ssr and broader topics.
  - name: "ğŸ™ Help"
    url: https://github.com/brillout/vite-plugin-sssr/discussions
    about: Use GitHub discussions to get help.
