blank_issues_enabled: false
contact_links:
  - name: "ğŸ™ Help & Questions"
    url: https://github.com/brillout/vite-plugin-ssr/discussions
    about: Get help and ask questions.
  - name: "ğŸ’¬ Chit-chat"
    url: https://discord.com/invite/hfHhnJyVg8
    about: Casual conversations about vite-plugin-ssr and broader topics.
