blank_issues_enabled: false
contact_links:
  - name: "ğŸ™ Help"
    url: https://github.com/brillout/vite-plugin-ssr/discussions
    about: Get help.
  - name: "ğŸ’¬ Chit-chat"
    url: https://discord.com/invite/dSDMGGJZQy
    about: Casual conversations about vite-plugin-ssr and broader topics related to frontend development/frameworks/tools.
