blank_issues_enabled: false
contact_links:
  - name: "ğŸ™ Help"
    url: https://github.com/brillout/vite-plugin-ssr/discussions
    about: Get help.
  - name: "ğŸ’¬ Discussions"
    url: https://discord.com/invite/dSDMGGJZQy
    about: Discuss & criticize vite-plugin-ssr, show us what you're building, chit-chat with maintainers, ...
