name = "vite-ssr-worker"
type = "webpack"
account_id = ""
workers_dev = true
webpack_config = "./webpack.config.js"
compatibility_date = "2021-09-29"

[site]
bucket = "./dist/client"
entry-point = "./worker"
