name: Auto-merge Dependabot PRs

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]

jobs:
  auto-merge-dependabot:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Merge Dependabot PR
        run: gh pr merge --auto --squash "$PR_TITLE (#$PR_NUMBER)"
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
