name: Docs
on:
  push:
    # We only run this GitHub action upon new commits to `main`
    branches:
      - main
    # We only run this GitHub action if there are changes in the docs directory
    paths:
      - packages/vike.dev/**
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run docs:build

      - run: pnpm run docs:test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: packages/vike.dev/dist/client
          # Remove previous build files
          clean: true
          # Remove history â€” avoiding exploding Git repository size
          single-commit: true
          # Do not remove the `.nojekyll` file: we have manually added an empty `.nojekyll` file at the root of the `gh-pages` branch and we don't want having to re-create it after each build.
          clean-exclude: |
            .nojekyll
permissions:
  contents: write
